openapi: 3.0.3
info:
  title: FLICS Adapter API
  version: 1.0.0

paths:
  /task/status:
    post:
      operationId: GetTask
      summary: Retrieve status of a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTaskRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTaskResponse'

components:
  schemas:
    Metadata:
      type: object
      properties:
        x_request_id:
          type: string
        custom_fields:
          type: object
          additionalProperties:
            type: string

    GetTaskRequest:
      type: object
      properties:
        specification_version:
          type: string
        timestamp:
          type: integer
        metadata:
          $ref: '#/components/schemas/Metadata'
        platform_job_id:
          type: string
        platform_url:
          type: string
      required:
        - specification_version
        - timestamp
        - metadata
        - platform_job_id
        - platform_url

    GetTaskResponse:
      type: object
      oneOf:
        - $ref: '#/components/schemas/Success'
        - $ref: '#/components/schemas/Error_'

    Success:
      type: object
      properties:
        status:
          type: string
        details:
          type: object
      required: [status]

    Error_:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required: [code, message]
